import type { Theme } from '../theme.types';

export const darkTheme: Theme = {
  name: 'dark',
  colors: {
    background: '#000000',
    surface: '#0A0A0A',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A3AA',
    textMuted: '#8F929A',
    accent: '#FA9414',
    accentMuted: '#C97510',
    border: '#FA9414',
    divider: '#2A2D33',
    kpiCardBackground: '#000000',
    kpiCardBorder: '#FA9414',
    interactionCount: '#8F929A',
    headerBackground: '#FFFFFF',
    headerLogo: '#000000',
  },
  typography: {
    logo: 24,
    title: 22,
    subtitle: 12,
    body: 12,
    label: 9,
    kpiValue: 20,
    kpiLabel: 9,
    interactionIcon: 24,
    interactionCount: 9,
    editorTag: 8,
    editorName: 11,
    editorRole: 9,
    swipeHint: 10,
  },
  layout: {
    headerFlex: 5,
    row1Flex: 20,
    row2Flex: 50,
    row3Flex: 25,
    row1Col1WidthPercent: 70,
    row1Col2WidthPercent: 30,
    row2Col1WidthPercent: 90,
    row2Col2WidthPercent: 10,
    screenPaddingHorizontal: 16,
    screenPaddingVertical: 8,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
