import type { Theme } from '../theme.types';

export const lightTheme: Theme = {
  name: 'light',
  colors: {
    background: '#F5F5F6',
    surface: '#FFFFFF',
    textPrimary: '#111111',
    textSecondary: '#4A4D55',
    textMuted: '#6B6E76',
    accent: '#C97510',
    accentMuted: '#FA9414',
    border: '#C97510',
    divider: '#D8DADF',
    kpiCardBackground: '#FFFFFF',
    kpiCardBorder: '#C97510',
    interactionCount: '#6B6E76',
    headerBackground: '#111111',
    headerLogo: '#FFFFFF',
  },
  typography: {
    logo: 24,
    title: 22,
    subtitle: 12,
    body: 12,
    label: 9,
    kpiValue: 20,
    kpiLabel: 9,
    interactionIcon: 24,
    interactionCount: 9,
    editorTag: 8,
    editorName: 11,
    editorRole: 9,
    swipeHint: 10,
  },
  layout: {
    headerFlex: 5,
    row1Flex: 20,
    row2Flex: 50,
    row3Flex: 25,
    row1Col1WidthPercent: 70,
    row1Col2WidthPercent: 30,
    row2Col1WidthPercent: 90,
    row2Col2WidthPercent: 10,
    screenPaddingHorizontal: 16,
    screenPaddingVertical: 8,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
};
